# Código para apresentar as informações de uma variável
var1 = input('Digite qualquer coisa: ')
print('Tipo primitivo: {}'.format(type(var1)))
print('Só tem espaços?: {}'.format(var1.isspace()))
print('É um número? {}'.format(var1.isnumeric()))
print('É um alfabético? {}'.format(var1.isalpha()))
print('É um alfanumérico? {}'.format(var1.isalnum()))
print('Esta em maiúsculas? {}'.format(var1.isupper()))
print('Esta em minúsculas? {}'.format(var1.islower()))
print('Esta em capitalizada? {}'.format(var1.istitle()))